name: cruzhacks-2021-function-template

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linter: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.0
      - name: Install Dependencies
        run: |
            cd functions
            yarn install --frozen-lockfile
      - name: Running linter
        run: |
            cd functions 
            npm run lint
  tests: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.0
      - name: Install Dependencies
        run: |
            cd functions
            yarn install --frozen-lockfile 
      - name: Executing Tests 
        run: |
            cd functions 
            npm run test:ci
  auto-deploy:
    runs-on: ubuntu-latest
    needs: [tests, linter]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.0
      - name: Install Dependencies
        run: |
            cd functions
            yarn install --frozen-lockfile
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions #TODO: specify function you want to deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
